load("//cuttlefish/bazel:rules.bzl", "cf_cc_library")

package(
    default_visibility = ["//:android_cuttlefish"],
)

exports_files([".clang-tidy"])

cf_cc_library(
    name = "android_build",
    hdrs = ["android_build.h"],
    deps = [
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build:image_provider",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "android_build_partition",
    srcs = ["android_build_partition.cc"],
    hdrs = ["android_build_partition.h"],
    deps = [
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_ab_status",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_availability",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_source",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_type",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "android_builds",
    srcs = ["android_builds.cc"],
    hdrs = ["android_builds.h"],
    deps = [
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cf_cc_library(
    name = "android_product_dir",
    srcs = ["android_product_dir.cc"],
    hdrs = ["android_product_dir.h"],
    deps = [
        "//cuttlefish/common/libs/utils:files",
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "android_dist_build",
    srcs = ["android_dist_build.cc"],
    hdrs = ["android_dist_build.h"],
    deps = [
        "//cuttlefish/common/libs/utils:files",
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build",
        "//cuttlefish/host/commands/assemble_cvd/android_build:android_product_dir",
        "//cuttlefish/host/commands/assemble_cvd/android_build:image_provider",
        "//cuttlefish/host/commands/assemble_cvd/android_build:img_zip",
        "//cuttlefish/host/commands/assemble_cvd/android_build:target_files",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "fetched_android_build",
    srcs = ["fetched_android_build.cc"],
    hdrs = ["fetched_android_build.h"],
    deps = [
        "//cuttlefish/common/libs/key_equals_value",
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build",
        "//cuttlefish/host/commands/assemble_cvd/android_build:image_provider",
        "//cuttlefish/host/commands/assemble_cvd/android_build:img_zip",
        "//cuttlefish/host/commands/assemble_cvd/android_build:target_files",
        "//cuttlefish/host/libs/config:fetcher_config",
        "//cuttlefish/host/libs/config:file_source",
        "//libbase",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "find_build_archive",
    srcs = ["find_build_archive.cc"],
    hdrs = ["find_build_archive.h"],
    deps = [
        "//cuttlefish/common/libs/utils:files",
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/libs/config:build_archive",
        "//cuttlefish/host/libs/config:fetcher_config",
        "//cuttlefish/host/libs/config:file_source",
        "//cuttlefish/host/libs/zip:zip_file",
        "//cuttlefish/host/libs/zip/libzip_cc:archive",
        "@abseil-cpp//absl/strings",
    ],
)

cf_cc_library(
    name = "identify_partitions",
    srcs = ["identify_partitions.cc"],
    hdrs = ["identify_partitions.h"],
    deps = [
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build",
        "//cuttlefish/host/commands/assemble_cvd/android_build:android_build_partition",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_ab_status",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_availability",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_source",
        "//cuttlefish/host/commands/assemble_cvd/android_build:partition_type",
        "@abseil-cpp//absl/strings",
        "@android_system_core//:liblp",
        "@fmt",
    ],
)

cf_cc_library(
    name = "image_provider",
    srcs = ["image_provider.cc"],
    hdrs = ["image_provider.h"],
    deps = [
        "//cuttlefish/common/libs/utils:result",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "img_zip",
    srcs = ["img_zip.cc"],
    hdrs = ["img_zip.h"],
    deps = [
        "//cuttlefish/common/libs/key_equals_value",
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd:guest_config_cc_proto",
        "//cuttlefish/host/commands/assemble_cvd/android_build:find_build_archive",
        "//cuttlefish/host/commands/assemble_cvd/android_build:image_provider",
        "//cuttlefish/host/libs/config:build_archive",
        "//cuttlefish/host/libs/config:fetcher_config",
        "//cuttlefish/host/libs/config:file_source",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
        "@protobuf",
    ],
)

cf_cc_library(
    name = "partition_ab_status",
    srcs = ["partition_ab_status.cc"],
    hdrs = ["partition_ab_status.h"],
    deps = [
        "@fmt",
    ],
)

cf_cc_library(
    name = "partition_availability",
    srcs = ["partition_availability.cc"],
    hdrs = ["partition_availability.h"],
    deps = [
        "@fmt",
    ],
)

cf_cc_library(
    name = "target_files",
    srcs = ["target_files.cc"],
    hdrs = ["target_files.h"],
    deps = [
        "//cuttlefish/common/libs/key_equals_value",
        "//cuttlefish/common/libs/utils:result",
        "//cuttlefish/host/commands/assemble_cvd/android_build:find_build_archive",
        "//cuttlefish/host/commands/assemble_cvd/android_build:image_provider",
        "//cuttlefish/host/libs/config:build_archive",
        "//cuttlefish/host/libs/config:fetcher_config",
        "//cuttlefish/host/libs/config:file_source",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@fmt",
    ],
)

cf_cc_library(
    name = "partition_source",
    srcs = ["partition_source.cc"],
    hdrs = ["partition_source.h"],
    deps = [
        "@fmt",
    ],
)

cf_cc_library(
    name = "partition_type",
    srcs = ["partition_type.cc"],
    hdrs = ["partition_type.h"],
    deps = [
        "@fmt",
    ],
)
