load("//cuttlefish/bazel:rules.bzl", "cf_cc_library")

package(
    default_visibility = ["//:android_cuttlefish"],
)

exports_files([".clang-tidy"])

cf_cc_library(
    name = "partition_ab_status",
    srcs = ["partition_ab_status.cc"],
    hdrs = ["partition_ab_status.h"],
    deps = [
        "@fmt",
    ],
)

cf_cc_library(
    name = "partition_availability",
    srcs = ["partition_availability.cc"],
    hdrs = ["partition_availability.h"],
    deps = [
        "@fmt",
    ],
)

cf_cc_library(
    name = "partition_source",
    srcs = ["partition_source.cc"],
    hdrs = ["partition_source.h"],
    deps = [
        "@fmt",
    ],
)

cf_cc_library(
    name = "partition_type",
    srcs = ["partition_type.cc"],
    hdrs = ["partition_type.h"],
    deps = [
        "@fmt",
    ],
)
